# Generated by Django 4.0.4 on 2022-05-22 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bloodsample_bloodwork_examiner_medicalrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonor',
            name='bloodType',
            field=models.CharField(choices=[('A_POSITIVE', 'A_POSITIVE'), ('A_NEGATIVE', 'A_NEGATIVE'), ('O_POSITIVE', 'O_POSITIVE'), ('O_NEGATIVE', 'O_NEGATIVE'), ('B_POSITIVE', 'B_POSITIVE'), ('B_NEGATIVE', 'B_NEGATIVE'), ('AB_POSITIVE', 'AB_POSITIVE'), ('AB_NEGATIVE', 'AB_NEGATIVE'), ('OTHER', 'OTHER')], default='O_POSITIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='bloodreceiver',
            name='bloodType',
            field=models.CharField(choices=[('A_POSITIVE', 'A_POSITIVE'), ('A_NEGATIVE', 'A_NEGATIVE'), ('O_POSITIVE', 'O_POSITIVE'), ('O_NEGATIVE', 'O_NEGATIVE'), ('B_POSITIVE', 'B_POSITIVE'), ('B_NEGATIVE', 'B_NEGATIVE'), ('AB_POSITIVE', 'AB_POSITIVE'), ('AB_NEGATIVE', 'AB_NEGATIVE'), ('OTHER', 'OTHER')], default='O_POSITIVE', max_length=20),
        ),
        migrations.AlterField(
            model_name='examiner',
            name='bloodType',
            field=models.CharField(choices=[('A_POSITIVE', 'A_POSITIVE'), ('A_NEGATIVE', 'A_NEGATIVE'), ('O_POSITIVE', 'O_POSITIVE'), ('O_NEGATIVE', 'O_NEGATIVE'), ('B_POSITIVE', 'B_POSITIVE'), ('B_NEGATIVE', 'B_NEGATIVE'), ('AB_POSITIVE', 'AB_POSITIVE'), ('AB_NEGATIVE', 'AB_NEGATIVE'), ('OTHER', 'OTHER')], default='O_POSITIVE', max_length=20),
        ),
    ]
