# Generated by Django 4.0.4 on 2022-05-24 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('handy_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='products_images/default.png', upload_to='products_images')),
            ],
        ),
        migrations.AlterField(
            model_name='handyuser',
            name='image',
            field=models.ImageField(default='users_images/default.png', null=True, upload_to='users_images'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='handy_api.productimage'),
        ),
    ]
